"""fix

Revision ID: c519b0876023
Revises: 8ad565a1fb4e
Create Date: 2023-05-08 22:20:40.630864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c519b0876023'
down_revision = '8ad565a1fb4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repo_test', table_name='repo')
    op.drop_column('repo', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('test', sa.VARCHAR(), nullable=True))
    op.create_index('ix_repo_test', 'repo', ['test'], unique=False)
    # ### end Alembic commands ###
