"""repo path unique

Revision ID: ca27d2ebeab4
Revises: c519b0876023
Create Date: 2023-05-08 23:03:39.800793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca27d2ebeab4'
down_revision = 'c519b0876023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repo_path', table_name='repo')
    op.create_index(op.f('ix_repo_path'), 'repo', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_path'), table_name='repo')
    op.create_index('ix_repo_path', 'repo', ['path'], unique=False)
    # ### end Alembic commands ###
